# .github/actions/rust-setup/action.yml
name: "Rust Setup Action"
description: "Setup Rust toolchain with caching"

inputs:
  toolchain:
    description: "Rust toolchain to use (stable, beta, nightly)"
    required: false
    default: "stable"
  components:
    description: "Rust components to install"
    required: false

runs:
  using: "composite"
  steps:
    - name: Cache cargo registry and target
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Install Rust Toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ inputs.toolchain }}
        components: ${{ inputs.components }}
