name: Sqlx Setup
description: "Setup Sqlx toolchain with caching"

inputs:
  working-directory:
    description: "Working directory"
    required: false

runs:
  using: "composite"
  steps:
    - name: Check and Install sqlx-cli
      run: |
        if ! command -v sqlx &> /dev/null; then
          cargo install sqlx-cli --no-default-features --features native-tls,postgres
        else
          echo "Sqlx CLI is already installed."
        fi
      shell: bash

    - name: Run database migrations
      run: sqlx migrate run
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - name: SQLx offline metadata cache
      id: cache-sqlx
      uses: actions/cache@v4
      with:
        path: ${{ inputs.working-directory }}/.sqlx
        key: ${{ runner.os }}-sqlx-${{ hashFiles('${{ inputs.working-directory }}/migrations/**') }}

    - name: Generate SQLx offline metadata
      if: steps.cache-sqlx.outputs.cache-hit != 'true'
      run: cargo sqlx prepare
      shell: bash
      working-directory: ${{ inputs.working-directory }}
