name: Publish Docker Image

on:
  push:
  pull_request:
    branches: [main]

jobs:
  # axum-api:
  #   uses: ./.github/workflows/axum-api.yml
  svelte-ui:
    uses: ./.github/workflows/svelte-ui.yml
  build:
    needs:
      # - axum-api
      - svelte-ui
    runs-on: ubuntu-22.04
    steps:
      # Download build artifacts
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
      - run: ls -R artifacts
      # - uses: actions/download-artifact@v4
      #   with:
      #     name: svelte_build_output
      #     path: ui

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3

      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.repository_owner }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Build
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: .
      #     file: ./docker-context/Dockerfile
      #     push: true
      #     tags: selfhosted:latest

      # - name: Inspect
      #   run: |
      #     docker image inspect selfhosted:latest
