name: Publish Docker Image

on:
  push:
  pull_request:
    branches: [main]

defaults:
  run:
    working-directory: docker-context

jobs:
  # JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    # Required permissions
    permissions:
      pull-requests: read
    # Set job outputs to values from filter step
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      # For pull requests it's not necessary to checkout the code
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            backend:
              - 'backend/**'
            frontend:
              - 'frontend/**'

  axum-api:
    needs: changes
    if: ${{ needs.changes.outputs.backend == 'true' }}
    uses: ./.github/workflows/axum-api.yml

  svelte-ui:
    needs: changes
    if: ${{ needs.changes.outputs.frontend == 'true' }}
    uses: ./.github/workflows/svelte-ui.yml

  build:
    needs: [axum-api, svelte-ui]
    runs-on: ubuntu-22.04
    steps:
      # Download build artifacts
      - uses: actions/download-artifact@v4
        with:
          name: axum_build_binary
          path: api
      - uses: actions/download-artifact@v4
        with:
          name: svelte_build_output
          path: ui

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: selfhosted:latest

      - name: Inspect
        run: |
          docker image inspect selfhosted:latest
