name: Publish Docker Image

on:
  push:
  pull_request:
    branches: [main]

defaults:
  run:
    working-directory: devops

jobs:
  axum-api:
    uses: ./.github/workflows/axum-api.yml
  svelte-ui:
    uses: ./.github/workflows/svelte-ui.yml
  build:
    needs: [axum-api, svelte-ui]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Display structure of downloaded files
        run: ls -R artifacts
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: selfhosted:latest

      - name: Inspect
        run: |
          docker image inspect selfhosted:latest
