name: Release

on:
  push:
  pull_request:
    branches: [main]

jobs:
  axum-api:
    uses: ./.github/workflows/axum-api.yml
  build:
    runs-on: ubuntu-22.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      # Step 1: Check out the code
      - uses: actions/download-artifact@v4
        with:
          name: svelte_build_output
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path: ui
      - name: Deploy Check
        run: |
          ls -a
