name: UI Build
on:
  push:
  pull_request:
    branches: [main]

defaults:
  run:
    working-directory: sveltekit-ui

jobs:
  ui_build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [22]
    steps:
      # Step 1: Check out the code
      - uses: actions/checkout@v4
      # Step 2: Install pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      # Step 3: Install Node.js and cache dependencies
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
          cache-dependency-path: sveltekit-ui/pnpm-lock.yaml
      # Step 4: Install dependencies
      - name: Install dependencies
        run: pnpm install
      # Step 5: Build
      - name: Build
        run: pnpm run build
      # Step 6: Upload build artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sveltekit-output-files
          path: |
            sveltekit-ui/build
            sveltekit-ui/package.json
            sveltekit-ui/node_modules
